// Phone country selector data
// Copied VERBATIM from design-reference/.../js/primitives.jsx PHONE_COUNTRIES

export interface PhoneCountry {
  code: string; // ISO 3166-1 alpha-2 two-letter country code
  name: string;
  dial: string; // "+211"
  color: string; // CSS hex color for the flag box background
}

// List of countries with phone codes
export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "AD", name: "Andorra", dial: "+376", color: "#1F3A93" },
  {
    code: "AE",
    name: "United Arab Emirates",
    dial: "+971",
    color: "#1F3A93",
  },
  { code: "AF", name: "Afghanistan", dial: "+93", color: "#1F3A93" },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    dial: "+1-268",
    color: "#1F3A93",
  },
  { code: "AI", name: "Anguilla", dial: "+1-264", color: "#1F3A93" },
  { code: "AL", name: "Albania", dial: "+355", color: "#1F3A93" },
  { code: "AM", name: "Armenia", dial: "+374", color: "#1F3A93" },
  { code: "AO", name: "Angola", dial: "+244", color: "#1F3A93" },
  { code: "AQ", name: "Antarctica", dial: "+672", color: "#1F3A93" },
  { code: "AR", name: "Argentina", dial: "+54", color: "#1F3A93" },
  { code: "AS", name: "American Samoa", dial: "+1-684", color: "#1F3A93" },
  { code: "AT", name: "Austria", dial: "+43", color: "#1F3A93" },
  {
    code: "AU",
    name: "Australia",
    dial: "+61",

    color: "#1F3A93",
  },
  { code: "AW", name: "Aruba", dial: "+297", color: "#1F3A93" },
  { code: "AX", name: "Alland Islands", dial: "+358", color: "#1F3A93" },
  { code: "AZ", name: "Azerbaijan", dial: "+994", color: "#1F3A93" },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    dial: "+387",
    color: "#1F3A93",
  },
  { code: "BB", name: "Barbados", dial: "+1-246", color: "#1F3A93" },
  { code: "BD", name: "Bangladesh", dial: "+880", color: "#1F3A93" },
  { code: "BE", name: "Belgium", dial: "+32", color: "#1F3A93" },
  { code: "BF", name: "Burkina Faso", dial: "+226", color: "#1F3A93" },
  { code: "BG", name: "Bulgaria", dial: "+359", color: "#1F3A93" },
  { code: "BH", name: "Bahrain", dial: "+973", color: "#1F3A93" },
  { code: "BI", name: "Burundi", dial: "+257", color: "#1F3A93" },
  { code: "BJ", name: "Benin", dial: "+229", color: "#1F3A93" },
  { code: "BL", name: "Saint Barthelemy", dial: "+590", color: "#1F3A93" },
  { code: "BM", name: "Bermuda", dial: "+1-441", color: "#1F3A93" },
  { code: "BN", name: "Brunei Darussalam", dial: "+673", color: "#1F3A93" },
  { code: "BO", name: "Bolivia", dial: "+591", color: "#1F3A93" },
  { code: "BR", name: "Brazil", dial: "+55", color: "#1F3A93" },
  { code: "BS", name: "Bahamas", dial: "+1-242", color: "#1F3A93" },
  { code: "BT", name: "Bhutan", dial: "+975", color: "#1F3A93" },
  { code: "BV", name: "Bouvet Island", dial: "+47", color: "#1F3A93" },
  { code: "BW", name: "Botswana", dial: "+267", color: "#1F3A93" },
  { code: "BY", name: "Belarus", dial: "+375", color: "#1F3A93" },
  { code: "BZ", name: "Belize", dial: "+501", color: "#1F3A93" },
  {
    code: "CA",
    name: "Canada",
    dial: "+1",

    color: "#1F3A93",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    dial: "+61",
    color: "#1F3A93",
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    dial: "+243",
    color: "#1F3A93",
  },
  {
    code: "CF",
    name: "Central African Republic",
    dial: "+236",
    color: "#1F3A93",
  },
  {
    code: "CG",
    name: "Congo, Republic of the",
    dial: "+242",
    color: "#1F3A93",
  },
  { code: "CH", name: "Switzerland", dial: "+41", color: "#1F3A93" },
  { code: "CI", name: "Cote d'Ivoire", dial: "+225", color: "#1F3A93" },
  { code: "CK", name: "Cook Islands", dial: "+682", color: "#1F3A93" },
  { code: "CL", name: "Chile", dial: "+56", color: "#1F3A93" },
  { code: "CM", name: "Cameroon", dial: "+237", color: "#1F3A93" },
  { code: "CN", name: "China", dial: "+86", color: "#1F3A93" },
  { code: "CO", name: "Colombia", dial: "+57", color: "#1F3A93" },
  { code: "CR", name: "Costa Rica", dial: "+506", color: "#1F3A93" },
  { code: "CU", name: "Cuba", dial: "+53", color: "#1F3A93" },
  { code: "CV", name: "Cape Verde", dial: "+238", color: "#1F3A93" },
  { code: "CW", name: "Curacao", dial: "+599", color: "#1F3A93" },
  { code: "CX", name: "Christmas Island", dial: "+61", color: "#1F3A93" },
  { code: "CY", name: "Cyprus", dial: "+357", color: "#1F3A93" },
  { code: "CZ", name: "Czech Republic", dial: "+420", color: "#1F3A93" },
  {
    code: "DE",
    name: "Germany",
    dial: "+49",

    color: "#1F3A93",
  },
  { code: "DJ", name: "Djibouti", dial: "+253", color: "#1F3A93" },
  { code: "DK", name: "Denmark", dial: "+45", color: "#1F3A93" },
  { code: "DM", name: "Dominica", dial: "+1-767", color: "#1F3A93" },
  {
    code: "DO",
    name: "Dominican Republic",
    dial: "+1-809",
    color: "#1F3A93",
  },
  { code: "DZ", name: "Algeria", dial: "+213", color: "#1F3A93" },
  { code: "EC", name: "Ecuador", dial: "+593", color: "#1F3A93" },
  { code: "EE", name: "Estonia", dial: "+372", color: "#1F3A93" },
  { code: "EG", name: "Egypt", dial: "+20", color: "#1F3A93" },
  { code: "EH", name: "Western Sahara", dial: "+212", color: "#1F3A93" },
  { code: "ER", name: "Eritrea", dial: "+291", color: "#1F3A93" },
  { code: "ES", name: "Spain", dial: "+34", color: "#1F3A93" },
  { code: "ET", name: "Ethiopia", dial: "+251", color: "#1F3A93" },
  { code: "FI", name: "Finland", dial: "+358", color: "#1F3A93" },
  { code: "FJ", name: "Fiji", dial: "+679", color: "#1F3A93" },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    dial: "+500",
    color: "#1F3A93",
  },
  {
    code: "FM",
    name: "Micronesia, Federated States of",
    dial: "+691",
    color: "#1F3A93",
  },
  { code: "FO", name: "Faroe Islands", dial: "+298", color: "#1F3A93" },
  {
    code: "FR",
    name: "France",
    dial: "+33",

    color: "#1F3A93",
  },
  { code: "GA", name: "Gabon", dial: "+241", color: "#1F3A93" },
  { code: "GB", name: "United Kingdom", dial: "+44", color: "#1F3A93" },
  { code: "GD", name: "Grenada", dial: "+1-473", color: "#1F3A93" },
  { code: "GE", name: "Georgia", dial: "+995", color: "#1F3A93" },
  { code: "GF", name: "French Guiana", dial: "+594", color: "#1F3A93" },
  { code: "GG", name: "Guernsey", dial: "+44", color: "#1F3A93" },
  { code: "GH", name: "Ghana", dial: "+233", color: "#1F3A93" },
  { code: "GI", name: "Gibraltar", dial: "+350", color: "#1F3A93" },
  { code: "GL", name: "Greenland", dial: "+299", color: "#1F3A93" },
  { code: "GM", name: "Gambia", dial: "+220", color: "#1F3A93" },
  { code: "GN", name: "Guinea", dial: "+224", color: "#1F3A93" },
  { code: "GP", name: "Guadeloupe", dial: "+590", color: "#1F3A93" },
  { code: "GQ", name: "Equatorial Guinea", dial: "+240", color: "#1F3A93" },
  { code: "GR", name: "Greece", dial: "+30", color: "#1F3A93" },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    dial: "+500",
    color: "#1F3A93",
  },
  { code: "GT", name: "Guatemala", dial: "+502", color: "#1F3A93" },
  { code: "GU", name: "Guam", dial: "+1-671", color: "#1F3A93" },
  { code: "GW", name: "Guinea-Bissau", dial: "+245", color: "#1F3A93" },
  { code: "GY", name: "Guyana", dial: "+592", color: "#1F3A93" },
  { code: "HK", name: "Hong Kong", dial: "+852", color: "#1F3A93" },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    dial: "+672",
    color: "#1F3A93",
  },
  { code: "HN", name: "Honduras", dial: "+504", color: "#1F3A93" },
  { code: "HR", name: "Croatia", dial: "+385", color: "#1F3A93" },
  { code: "HT", name: "Haiti", dial: "+509", color: "#1F3A93" },
  { code: "HU", name: "Hungary", dial: "+36", color: "#1F3A93" },
  { code: "ID", name: "Indonesia", dial: "+62", color: "#1F3A93" },
  { code: "IE", name: "Ireland", dial: "+353", color: "#1F3A93" },
  { code: "IL", name: "Israel", dial: "+972", color: "#1F3A93" },
  { code: "IM", name: "Isle of Man", dial: "+44", color: "#1F3A93" },
  { code: "IN", name: "India", dial: "+91", color: "#1F3A93" },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    dial: "+246",
    color: "#1F3A93",
  },
  { code: "IQ", name: "Iraq", dial: "+964", color: "#1F3A93" },
  {
    code: "IR",
    name: "Iran, Islamic Republic of",
    dial: "+98",
    color: "#1F3A93",
  },
  { code: "IS", name: "Iceland", dial: "+354", color: "#1F3A93" },
  { code: "IT", name: "Italy", dial: "+39", color: "#1F3A93" },
  { code: "JE", name: "Jersey", dial: "+44", color: "#1F3A93" },
  { code: "JM", name: "Jamaica", dial: "+1-876", color: "#1F3A93" },
  { code: "JO", name: "Jordan", dial: "+962", color: "#1F3A93" },
  {
    code: "JP",
    name: "Japan",
    dial: "+81",

    color: "#1F3A93",
  },
  { code: "KE", name: "Kenya", dial: "+254", color: "#1F3A93" },
  { code: "KG", name: "Kyrgyzstan", dial: "+996", color: "#1F3A93" },
  { code: "KH", name: "Cambodia", dial: "+855", color: "#1F3A93" },
  { code: "KI", name: "Kiribati", dial: "+686", color: "#1F3A93" },
  { code: "KM", name: "Comoros", dial: "+269", color: "#1F3A93" },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    dial: "+1-869",
    color: "#1F3A93",
  },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    dial: "+850",
    color: "#1F3A93",
  },
  { code: "KR", name: "Korea, Republic of", dial: "+82", color: "#1F3A93" },
  { code: "KW", name: "Kuwait", dial: "+965", color: "#1F3A93" },
  { code: "KY", name: "Cayman Islands", dial: "+1-345", color: "#1F3A93" },
  { code: "KZ", name: "Kazakhstan", dial: "+7", color: "#1F3A93" },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    dial: "+856",
    color: "#1F3A93",
  },
  { code: "LB", name: "Lebanon", dial: "+961", color: "#1F3A93" },
  { code: "LC", name: "Saint Lucia", dial: "+1-758", color: "#1F3A93" },
  { code: "LI", name: "Liechtenstein", dial: "+423", color: "#1F3A93" },
  { code: "LK", name: "Sri Lanka", dial: "+94", color: "#1F3A93" },
  { code: "LR", name: "Liberia", dial: "+231", color: "#1F3A93" },
  { code: "LS", name: "Lesotho", dial: "+266", color: "#1F3A93" },
  { code: "LT", name: "Lithuania", dial: "+370", color: "#1F3A93" },
  { code: "LU", name: "Luxembourg", dial: "+352", color: "#1F3A93" },
  { code: "LV", name: "Latvia", dial: "+371", color: "#1F3A93" },
  { code: "LY", name: "Libya", dial: "+218", color: "#1F3A93" },
  { code: "MA", name: "Morocco", dial: "+212", color: "#1F3A93" },
  { code: "MC", name: "Monaco", dial: "+377", color: "#1F3A93" },
  {
    code: "MD",
    name: "Moldova, Republic of",
    dial: "+373",
    color: "#1F3A93",
  },
  { code: "ME", name: "Montenegro", dial: "+382", color: "#1F3A93" },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    dial: "+590",
    color: "#1F3A93",
  },
  { code: "MG", name: "Madagascar", dial: "+261", color: "#1F3A93" },
  { code: "MH", name: "Marshall Islands", dial: "+692", color: "#1F3A93" },
  {
    code: "MK",
    name: "Macedonia, the Former Yugoslav Republic of",
    dial: "+389",
    color: "#1F3A93",
  },
  { code: "ML", name: "Mali", dial: "+223", color: "#1F3A93" },
  { code: "MM", name: "Myanmar", dial: "+95", color: "#1F3A93" },
  { code: "MN", name: "Mongolia", dial: "+976", color: "#1F3A93" },
  { code: "MO", name: "Macao", dial: "+853", color: "#1F3A93" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    dial: "+1-670",
    color: "#1F3A93",
  },
  { code: "MQ", name: "Martinique", dial: "+596", color: "#1F3A93" },
  { code: "MR", name: "Mauritania", dial: "+222", color: "#1F3A93" },
  { code: "MS", name: "Montserrat", dial: "+1-664", color: "#1F3A93" },
  { code: "MT", name: "Malta", dial: "+356", color: "#1F3A93" },
  { code: "MU", name: "Mauritius", dial: "+230", color: "#1F3A93" },
  { code: "MV", name: "Maldives", dial: "+960", color: "#1F3A93" },
  { code: "MW", name: "Malawi", dial: "+265", color: "#1F3A93" },
  { code: "MX", name: "Mexico", dial: "+52", color: "#1F3A93" },
  { code: "MY", name: "Malaysia", dial: "+60", color: "#1F3A93" },
  { code: "MZ", name: "Mozambique", dial: "+258", color: "#1F3A93" },
  { code: "NA", name: "Namibia", dial: "+264", color: "#1F3A93" },
  { code: "NC", name: "New Caledonia", dial: "+687", color: "#1F3A93" },
  { code: "NE", name: "Niger", dial: "+227", color: "#1F3A93" },
  { code: "NF", name: "Norfolk Island", dial: "+672", color: "#1F3A93" },
  { code: "NG", name: "Nigeria", dial: "+234", color: "#1F3A93" },
  { code: "NI", name: "Nicaragua", dial: "+505", color: "#1F3A93" },
  { code: "NL", name: "Netherlands", dial: "+31", color: "#1F3A93" },
  { code: "NO", name: "Norway", dial: "+47", color: "#1F3A93" },
  { code: "NP", name: "Nepal", dial: "+977", color: "#1F3A93" },
  { code: "NR", name: "Nauru", dial: "+674", color: "#1F3A93" },
  { code: "NU", name: "Niue", dial: "+683", color: "#1F3A93" },
  { code: "NZ", name: "New Zealand", dial: "+64", color: "#1F3A93" },
  { code: "OM", name: "Oman", dial: "+968", color: "#1F3A93" },
  { code: "PA", name: "Panama", dial: "+507", color: "#1F3A93" },
  { code: "PE", name: "Peru", dial: "+51", color: "#1F3A93" },
  { code: "PF", name: "French Polynesia", dial: "+689", color: "#1F3A93" },
  { code: "PG", name: "Papua New Guinea", dial: "+675", color: "#1F3A93" },
  { code: "PH", name: "Philippines", dial: "+63", color: "#1F3A93" },
  { code: "PK", name: "Pakistan", dial: "+92", color: "#1F3A93" },
  { code: "PL", name: "Poland", dial: "+48", color: "#1F3A93" },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    dial: "+508",
    color: "#1F3A93",
  },
  { code: "PN", name: "Pitcairn", dial: "+870", color: "#1F3A93" },
  { code: "PR", name: "Puerto Rico", dial: "+1", color: "#1F3A93" },
  {
    code: "PS",
    name: "Palestine, State of",
    dial: "+970",
    color: "#1F3A93",
  },
  { code: "PT", name: "Portugal", dial: "+351", color: "#1F3A93" },
  { code: "PW", name: "Palau", dial: "+680", color: "#1F3A93" },
  { code: "PY", name: "Paraguay", dial: "+595", color: "#1F3A93" },
  { code: "QA", name: "Qatar", dial: "+974", color: "#1F3A93" },
  { code: "RE", name: "Reunion", dial: "+262", color: "#1F3A93" },
  { code: "RO", name: "Romania", dial: "+40", color: "#1F3A93" },
  { code: "RS", name: "Serbia", dial: "+381", color: "#1F3A93" },
  { code: "RU", name: "Russian Federation", dial: "+7", color: "#1F3A93" },
  { code: "RW", name: "Rwanda", dial: "+250", color: "#1F3A93" },
  { code: "SA", name: "Saudi Arabia", dial: "+966", color: "#1F3A93" },
  { code: "SB", name: "Solomon Islands", dial: "+677", color: "#1F3A93" },
  { code: "SC", name: "Seychelles", dial: "+248", color: "#1F3A93" },
  { code: "SD", name: "Sudan", dial: "+249", color: "#1F3A93" },
  { code: "SE", name: "Sweden", dial: "+46", color: "#1F3A93" },
  { code: "SG", name: "Singapore", dial: "+65", color: "#1F3A93" },
  { code: "SH", name: "Saint Helena", dial: "+290", color: "#1F3A93" },
  { code: "SI", name: "Slovenia", dial: "+386", color: "#1F3A93" },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    dial: "+47",
    color: "#1F3A93",
  },
  { code: "SK", name: "Slovakia", dial: "+421", color: "#1F3A93" },
  { code: "SL", name: "Sierra Leone", dial: "+232", color: "#1F3A93" },
  { code: "SM", name: "San Marino", dial: "+378", color: "#1F3A93" },
  { code: "SN", name: "Senegal", dial: "+221", color: "#1F3A93" },
  { code: "SO", name: "Somalia", dial: "+252", color: "#1F3A93" },
  { code: "SR", name: "Suriname", dial: "+597", color: "#1F3A93" },
  { code: "SS", name: "South Sudan", dial: "+211", color: "#1F3A93" },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    dial: "+239",
    color: "#1F3A93",
  },
  { code: "SV", name: "El Salvador", dial: "+503", color: "#1F3A93" },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    dial: "+1-721",
    color: "#1F3A93",
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    dial: "+963",
    color: "#1F3A93",
  },
  { code: "SZ", name: "Swaziland", dial: "+268", color: "#1F3A93" },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    dial: "+1-649",
    color: "#1F3A93",
  },
  { code: "TD", name: "Chad", dial: "+235", color: "#1F3A93" },
  {
    code: "TF",
    name: "French Southern Territories",
    dial: "+262",
    color: "#1F3A93",
  },
  { code: "TG", name: "Togo", dial: "+228", color: "#1F3A93" },
  { code: "TH", name: "Thailand", dial: "+66", color: "#1F3A93" },
  { code: "TJ", name: "Tajikistan", dial: "+992", color: "#1F3A93" },
  { code: "TK", name: "Tokelau", dial: "+690", color: "#1F3A93" },
  { code: "TL", name: "Timor-Leste", dial: "+670", color: "#1F3A93" },
  { code: "TM", name: "Turkmenistan", dial: "+993", color: "#1F3A93" },
  { code: "TN", name: "Tunisia", dial: "+216", color: "#1F3A93" },
  { code: "TO", name: "Tonga", dial: "+676", color: "#1F3A93" },
  { code: "TR", name: "Turkey", dial: "+90", color: "#1F3A93" },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    dial: "+1-868",
    color: "#1F3A93",
  },
  { code: "TV", name: "Tuvalu", dial: "+688", color: "#1F3A93" },
  {
    code: "TW",
    name: "Taiwan",
    dial: "+886",
    color: "#1F3A93",
  },
  {
    code: "TZ",
    name: "United Republic of Tanzania",
    dial: "+255",
    color: "#1F3A93",
  },
  { code: "UA", name: "Ukraine", dial: "+380", color: "#1F3A93" },
  { code: "UG", name: "Uganda", dial: "+256", color: "#1F3A93" },
  {
    code: "US",
    name: "United States",
    dial: "+1",

    color: "#1F3A93",
  },
  { code: "UY", name: "Uruguay", dial: "+598", color: "#1F3A93" },
  { code: "UZ", name: "Uzbekistan", dial: "+998", color: "#1F3A93" },
  {
    code: "VA",
    name: "Holy See (Vatican City State)",
    dial: "+379",
    color: "#1F3A93",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    dial: "+1-784",
    color: "#1F3A93",
  },
  { code: "VE", name: "Venezuela", dial: "+58", color: "#1F3A93" },
  {
    code: "VG",
    name: "British Virgin Islands",
    dial: "+1-284",
    color: "#1F3A93",
  },
  {
    code: "VI",
    name: "US Virgin Islands",
    dial: "+1-340",
    color: "#1F3A93",
  },
  { code: "VN", name: "Vietnam", dial: "+84", color: "#1F3A93" },
  { code: "VU", name: "Vanuatu", dial: "+678", color: "#1F3A93" },
  { code: "WF", name: "Wallis and Futuna", dial: "+681", color: "#1F3A93" },
  { code: "WS", name: "Samoa", dial: "+685", color: "#1F3A93" },
  { code: "XK", name: "Kosovo", dial: "+383", color: "#1F3A93" },
  { code: "YE", name: "Yemen", dial: "+967", color: "#1F3A93" },
  { code: "YT", name: "Mayotte", dial: "+262", color: "#1F3A93" },
  { code: "ZA", name: "South Africa", dial: "+27", color: "#1F3A93" },
  { code: "ZM", name: "Zambia", dial: "+260", color: "#1F3A93" },
  { code: "ZW", name: "Zimbabwe", dial: "+263", color: "#1F3A93" },
];

export interface PhoneValue {
  dial: string;
  code: string;
  num: string;
}

// Default: South Sudan +211 (always the first/default country)
export const DEFAULT_PHONE: PhoneValue = {
  dial: "+211",
  code: "SS",
  num: "",
};

// Helper: combine dial + num into E.164-ish string
export function phoneE164(value: PhoneValue | null | undefined): string {
  const v = value ?? DEFAULT_PHONE;
  return v.dial + v.num;
}

// Helper: validate phone value, returns error string or ""
export function phoneError(
  value: PhoneValue | null | undefined,
  touched: boolean,
): string {
  if (!touched) return "";
  const num = value?.num ?? "";
  if (!num) return "Phone number is required";
  if (num.length < 7) return "Enter a valid phone number";
  return "";
}
